# -*- coding: utf-8 -*-
import os, json
BASE="/tmp/claude-0/-home-user-fl-family-law-authority/7ac3e289-c815-5f2d-9278-ecc0918a4dd6/scratchpad"
bodies=os.path.join(BASE,"bodies")
OUT=os.path.join(BASE,"final_posts"); os.makedirs(OUT,exist_ok=True)

# shell from an existing final page (header+footer+js, correct domain/nav)
shell=open(os.path.join(BASE,"final","blog.html")).read()
HEAD=shell.split("<main>",1)[0]
TAIL=shell.split("</main>",1)[1]

CTA=('\n  <div class="cta-band pink" style="margin-top:44px">\n'
 '    <div><h2>Talk it through before you sign anything</h2><p>Your intake goes straight to our team &mdash; start with a free consult or move straight ahead.</p></div>\n'
 '    <div style="display:flex;gap:10px;flex-wrap:wrap"><a href="/free-consult-intake/" class="btn btn-solid">Free consultation</a><a href="/get-started/" class="btn btn-outline-light">Get started</a></div>\n'
 '  </div>')

def esc(s): return s.replace("&","&amp;").replace("<","&lt;").replace(">","&gt;")

def render(p):
    blocks=[f'<p class="article-meta">Florida Family Law &middot; Attorney-reviewed</p>']
    for h,paras in p["body"]:
        blocks.append(f"<h2>{h}</h2>")
        for para in paras:
            blocks.append(f"<p>{para}</p>")
    blocks.append(f'<div class="callout pink"><strong>Bottom line:</strong> {p["bottom"]}</div>')
    prose="\n      ".join(blocks)
    main=(f'<main>\n\n<section class="page-hero tint-topic" style="border-top-color:{p["color"]}">\n'
     f'  <div class="wrap">\n    <div class="breadcrumb"><a href="/">Home</a> <span>/</span> <a href="/blog/">Blog</a> <span>/</span> {p["cat"]}</div>\n'
     f'    <span class="eyebrow" style="color:{p["color"]}">{p["cat"]}</span>\n    <h1>{p["h1"]}</h1>\n'
     f'    <p class="lede">{p["summary"]}</p>\n  </div>\n</section>\n\n'
     f'<section class="section paper"><div class="wrap article">\n  <div class="prose">\n      {prose}\n  </div>{CTA}\n</div></section>\n\n</main>')
    return HEAD+main+TAIL

POSTS=[
{"slug":"hidden-income-florida-child-support","cat":"Child Support","color":"var(--orange)","date":"2026-08-28T09:00:00",
 "mtitle":"Hidden Income in FL Child Support Cases | FMLG",
 "mdesc":"Retirement pay isn't the whole story. Learn how Florida courts calculate true income for child support when a parent has investments or hidden earnings.",
 "h1":"When Your Ex Says They Make Less Than They Do",
 "summary":"Florida child support isn't based on a pay stub alone — it's based on total gross income under §61.30, including retirement pay, investment income, and portfolio earnings. Here's how hidden or complex income gets uncovered and factored into a fair calculation.",
 "body":[
  ("The one number that can blow up your child support case",["Florida child support isn't calculated off a pay stub. It's calculated off total income — and when one parent's income is complicated, that single number becomes the whole fight.","We see this constantly: one parent has a clean W-2, the other has retirement pay plus an investment portfolio nobody has fully disclosed. The gap between what a parent says they make and what they actually make can be the difference between a support order that works and one that doesn't."]),
  ("Florida law counts all income, not just the paycheck",["Under Florida Statute §61.30, gross income for child support includes far more than salary. It includes bonuses, commissions, disability benefits, retirement and pension payments, rental income, and — critically — investment income, including dividends, interest, and capital gains.","If a parent has a brokerage account generating six figures a year on top of a stated retirement income, that account's earnings belong in the calculation. Florida courts don't let a parent's income disappear into an account just because it isn't a paycheck."]),
  ("What total income actually includes",["A parent drawing $120,000 a year from a pension might also be sitting on a portfolio that throws off another $80,000 to $100,000 in annual income. Combined, that's a completely different support number than the pension figure alone.","Tax returns, 1099s, and brokerage statements are where this gets resolved. Until those documents are in hand, any support number built on the stated income alone is a guess — and usually a low one."]),
  ("A real example: the $1,000-a-month gap",["We've worked cases where using only a parent's disclosed retirement income produced a support figure of roughly $200 a month. Once total income — including the undisclosed portfolio — was factored in using a reasonable estimate, that number jumped to $1,100 to $1,300 a month.","That's not a rounding error. That's the difference between a child getting the support they need and going without."]),
  ("Your three options when a co-parent's income is unclear",["You generally have three paths. First, negotiate using a reasonable estimated income and put it in writing, accepting some risk in exchange for speed. Second, bring in a neutral financial expert — a Certified Divorce Financial Analyst — to review the documents and issue an impartial opinion both sides agree to honor. Third, set a support floor based on undisputed income now, with a court-ordered adjustment once full financial discovery is complete.","None of these are wrong. They're trade-offs between speed and accuracy, and the right one depends on how much is at stake and how much conflict you can tolerate."]),
  ("Don't let “keep it simple” cost your child real support",["Wanting a fast, amicable divorce is a good instinct. But fast and fair aren't always the same thing when income is hidden behind retirement statements and brokerage accounts.","You can still move quickly. You just need someone looking at the actual numbers before you sign anything final."]),
 ],
 "bottom":"If your co-parent's income comes from more than a paycheck, don't let the divorce move faster than the financial discovery. A support order built on partial income is one you'll likely have to fix later — at your child's expense."},

{"slug":"florida-prenup-simplifies-divorce","cat":"Prenuptial Agreements","color":"var(--teal)","date":"2026-08-30T09:00:00",
 "mtitle":"Do Prenups Really Work in Florida Divorce? | FMLG",
 "mdesc":"A well-drafted prenup can turn a messy Florida divorce into a fast, low-conflict process. Here's what makes one enforceable — and what it can't decide for you.",
 "h1":"Prenups Aren't Just for the Wealthy",
 "summary":"A properly executed Florida prenuptial agreement under §61.079 can protect separate property and dramatically simplify divorce — but it can never predetermine child custody or support. Here's what a prenup actually locks in, what makes it enforceable, and where it stops.",
 "body":[
  ("The myth that prenups are only for the rich",["People picture prenups as something for celebrities and trust-fund kids. In practice, they're one of the most useful tools available to anyone entering a marriage with assets, a business, retirement accounts, or kids from a prior relationship.","A prenup isn't about planning to fail. It's about deciding the rules while you're both calm, instead of leaving a judge to decide them while you're not."]),
  ("What a prenup actually locks in — and what it can't",["A well-drafted, enforceable Florida prenuptial agreement under §61.079 typically does one job extremely well: it defines what stays separate property. Assets brought into the marriage — and the growth on those assets — can be protected from division, even after years of marriage.","That single provision can eliminate most of the fighting in a divorce. If the retirement account and the investments are already spoken for, there's often only one real asset left to negotiate: the marital home built together."]),
  ("Why this matters the day you actually divorce",["We've seen prenups do exactly what they're supposed to do — turn what could have been a drawn-out asset fight into a two-issue conversation. When the prenup is clean and enforceable, couples can move straight to the parts that actually need negotiating: parenting time and support.","That's the real value. Not preventing divorce. Shrinking it."]),
  ("The one thing a prenup will never decide: your kids",["Here's what a prenup cannot do, no matter how well it's drafted: decide parenting time, decision-making authority, or child support. Florida courts will not enforce a provision that predetermines custody or caps support below what a child actually needs — that's decided based on the child's circumstances at the time of divorce, not an agreement signed years earlier.","So if children are involved, expect a prenup to simplify the money conversation and leave the parenting conversation for later, on its own terms."]),
  ("How to know if your prenup will hold up",["Enforceability comes down to a few consistent things: full financial disclosure at the time of signing, no coercion or unequal bargaining power, and terms that aren't unconscionable. A prenup signed the night before the wedding, with no financial disclosure, is far more vulnerable than one negotiated months in advance with both parties represented.","If you're heading into divorce and have a prenup, the first question isn't what it says — it's whether it will hold up. That answer changes everything about how the rest of the case gets handled."]),
 ],
 "bottom":"A prenup doesn't make divorce painless, but a solid one makes it shorter, cheaper, and a lot less personal. If you have one, get it reviewed before you assume it protects what you think it protects."},

{"slug":"divorcing-with-a-special-needs-child-florida","cat":"Special Needs","color":"var(--chartreuse)","date":"2026-09-01T09:00:00",
 "mtitle":"Divorce and a Special-Needs Child in Florida | FMLG",
 "mdesc":"Custody, support, and decision-making look different when your child has special needs. Here's what to build into your Florida parenting plan and support order.",
 "h1":"Divorcing With a Special-Needs Child",
 "summary":"Divorcing parents of a special-needs child in Florida need a parenting plan and support order built around the child's actual care needs, not a standard 50/50 template. Here's what to cover: decision-making authority, therapy and medical costs, and protecting stability through the process.",
 "body":[
  ("A different kind of divorce math",["Every divorce involving kids requires a parenting plan and a support calculation. When a child has special needs — developmental delays, a disability, ongoing therapy — both of those documents have to work harder.","The standard templates for timesharing and support were built around a typical child. They don't automatically account for a child who needs speech therapy several times a week, or a parent who can't simply hand off care every other weekend without disrupting routines that took years to build."]),
  ("Why 50/50 isn't always the right starting point",["Equal timesharing is the default Florida courts lean toward, and for good reason — in most cases, it serves the child. But a special-needs child's stability often depends on consistency: the same home, the same routines, the same therapists, the same school.","That doesn't mean the other parent gets shut out. It means the parenting plan needs to be built around what actually keeps the child stable, with honest input from both parents about who is prepared to provide day-to-day care."]),
  ("Building decision-making authority into the plan",["Medical decisions, therapy providers, school placement, and IEP meetings all need a clear decision-maker in the plan. When one parent has historically handled these responsibilities and the other has stepped back, the parenting plan should reflect that reality, not paper over it.","Leaving decision-making vague to be worked out later is one of the most common mistakes we see. It creates conflict exactly when the child can least afford it."]),
  ("Support numbers have to account for the real cost of care",["Speech therapy, occupational therapy, specialized childcare, and medical costs beyond standard insurance coverage all belong in the support conversation. Florida's child support guidelines allow for these costs to be built into the order — but only if someone puts real numbers in front of the court.","If you're the parent managing daily care, don't assume the standard guideline number covers what your child actually needs. Get the actual costs documented."]),
  ("When one parent steps back: protecting the child anyway",["Sometimes one parent, for whatever reason, isn't equipped to take on day-to-day care of a child with significant needs. That's a hard reality, but it's better addressed directly in the parenting plan than left as an unspoken assumption.","A plan that's honest about who is doing the caregiving — and pays for it accordingly — protects the child far better than one built on wishful thinking about shared responsibility that isn't actually shared."]),
 ],
 "bottom":"A special-needs child doesn't fit a template. Build the parenting plan and the support order around the actual care your child needs, not the paperwork that's easiest to file."},

{"slug":"florida-relocation-order-vacated","cat":"Relocation","color":"var(--pink)","date":"2026-09-03T09:00:00",
 "mtitle":"Florida Relocation Order Vacated — Now What? | FMLG",
 "mdesc":"A relocation order can be undone months after the move. Here's what Florida law requires when a court vacates relocation and orders children back.",
 "h1":"When a Judge Reverses a Relocation Order",
 "summary":"Florida relocation orders can be vacated when the required statutory factor analysis is incomplete — even after a family has resettled. Here's why courts reverse relocation rulings, what vacating an order means for the children, and how to build an order that survives a second look.",
 "body":[
  ("Yes, a relocation order can be undone",["Most people assume once a judge approves a move, it's final. It isn't. Florida courts can — and do — vacate relocation orders, sometimes months after a family has already resettled hundreds of miles away.","When that happens, the order doesn't just stop the move going forward. It can require the children to return to where they came from."]),
  ("Why courts vacate relocation rulings",["A relocation order gets vacated when the original ruling didn't properly work through the required legal analysis — most commonly, when a judge's findings on the statutory relocation factors were incomplete or didn't hold up on review. Florida's relocation statute requires a genuine factor-by-factor analysis, not a general sense that the move seemed reasonable.","If that analysis is missing or thin, the order is vulnerable, no matter how settled the family has become in the new location."]),
  ("What “vacated” actually means for the family",["Vacating a relocation order resets the clock. The prior arrangement — before the move — is typically what governs again, at least temporarily, while a new, more thorough order gets drafted.","For the kids, that can mean returning to a prior home, school, and routine after already adjusting to a new one. It's disruptive, which is exactly why courts don't take vacating these orders lightly — and exactly why the original order needs to be built right the first time."]),
  ("The court doesn't let go of jurisdiction over a teenager",["One detail that surprises people: courts will maintain jurisdiction over a child right up to age 18, even a teen just months from turning 18. A pending relocation dispute doesn't just evaporate because a child is close to aging out.","If your case involves an older teen, don't assume the court will treat the relocation question as nearly moot. It won't."]),
  ("Building an order that survives the second time",["When a relocation order gets vacated and sent back, the redo isn't optional — it has to actually address every factor the first order missed. That means a real, documented analysis of each parent's stability, the child's ties to community and school, the reasons for the move, and the practical impact on the other parent's relationship with the child.","A shortcut the second time around just invites a second reversal."]),
 ],
 "bottom":"A relocation order is only as strong as the analysis behind it. If yours was thin, don't wait for the other side to challenge it — get it fixed before it gets vacated for you."},

{"slug":"florida-11-relocation-factors","cat":"Relocation","color":"var(--pink)","date":"2026-09-05T09:00:00",
 "mtitle":"Florida's 11 Relocation Factors Explained | FMLG",
 "mdesc":"Want to relocate with your kids — or stop your co-parent from moving them? Here are the 11 factors Florida courts use to decide, straight from §61.13001.",
 "h1":"The 11 Factors Florida Judges Weigh Before a Move",
 "summary":"Florida Statute §61.13001 requires courts to weigh 11 statutory factors before allowing a parent to relocate a child's principal residence more than 50 miles. Here's what those factors actually mean and what tends to win or lose a relocation case.",
 "body":[
  ("It's not just “can I move” — it's “can I take them”",["Under Florida Statute §61.13001, a parent doesn't need permission to move themselves anywhere. They need permission to move a child's principal residence more than 50 miles away for 60 or more consecutive days, unless the other parent agrees in writing or a court signs off.","That distinction trips people up constantly. You're always free to move. Taking the kids with you is the part that requires either agreement or a judge's order."]),
  ("The 11 factors, in plain English",["Florida courts weigh eleven factors, but they boil down to a few real questions: Is this move genuinely good for the child, or is it primarily about the parent's convenience or new relationship? What has each parent's involvement actually looked like day to day, not on paper? Can the relationship with the parent staying behind survive the distance, and is the moving parent actually willing to make that happen?","Courts also look hard at each parent's history of stability — housing, employment, school consistency — and whether the reasons given for the move are the real reasons or a story built for court."]),
  ("What actually wins and loses these cases",["The strongest relocation cases show a genuine, child-centered reason for the move — better schools, family support, a stable home — backed up by a track record of actually being the primary caregiver. The weakest cases lean on a new partner's house as the whole justification, especially when there's a pattern of frequent moves, job changes, or school disruptions beforehand.","Judges notice patterns. A parent who's moved many times in a short span is going to have a harder time arguing this move is the one that finally brings stability."]),
  ("The move has to be about the kids, not just a new life",["You're allowed to want a fresh start. But if the case is built entirely around what's better for you, expect the other side — and the court — to ask why the children should absorb that disruption. The strongest arguments connect the dots between the parent's new circumstances and a concrete, provable benefit to the child: better school ratings, a bigger support network, actual stability that's been missing.","Vague talk about quality of life without specifics rarely carries the day."]),
  ("What to do before you pack a single box",["If you're the one who wants to move, get the notice requirements right before you do anything else — written notice to the other parent, filed correctly, before the move, not after. If you're opposing a move, start documenting your involvement now: school pickups, medical appointments, the day-to-day proof that the current arrangement is working.","Either way, the case is won or lost on documentation, not intentions."]),
 ],
 "bottom":"Relocation cases are decided on facts about the child, not feelings about the move. Build your case around what actually happens to your kids, not around what you want your life to look like next."},

{"slug":"relocating-without-court-permission-florida","cat":"Relocation","color":"var(--orange)","date":"2026-09-07T09:00:00",
 "mtitle":"Moving Kids Without Court Permission in FL | FMLG",
 "mdesc":"Moved your kids before a judge said yes? Florida law doesn't reward it. Here's what unauthorized relocation actually does to your custody case.",
 "h1":"Why “Ask Forgiveness Later” Backfires",
 "summary":"Relocating a child's principal residence without written agreement or court permission violates Florida Statute §61.13001, and courts do not forgive it simply because time has passed. Here are the notice requirements, the consequences of skipping them, and how to handle an already-completed move.",
 "body":[
  ("The move that happens before the order",["It happens more than people expect: a parent moves the kids first and plans to sort out the legal paperwork later. Sometimes it's urgency. Sometimes it's the belief that once the kids are settled, a judge won't make them move again.","That belief is usually wrong, and it can cost far more than the move itself was worth."]),
  ("What Florida law actually requires before you go",["Florida Statute §61.13001 requires written notice to the other parent before relocating a child's principal residence more than 50 miles, or a written agreement, or a court order permitting the move. Sending a text message with a new address after the fact does not satisfy this. Neither does moving and hoping no one objects.","If you relocate without any of these in place, you've moved outside the boundaries the statute sets, regardless of how good your reasons were."]),
  ("Why judges don't forgive this easily",["Courts take unauthorized relocation seriously because the statute exists specifically to prevent parents from creating facts on the ground that pressure a favorable outcome. A judge isn't going to reward a parent for successfully relocating without permission just because the kids have now been in a new school for a while.","If anything, the unauthorized move becomes its own issue in the case, separate from whatever the underlying custody or relocation dispute already was."]),
  ("It doesn't just hurt your case — it follows the kids",["An unauthorized relocation, once acknowledged in a filing or admitted in testimony, becomes part of the permanent record the court considers when evaluating that parent's judgment and reliability going forward. It can undercut an otherwise strong relocation argument, even if the destination itself would have been approved through the proper process.","The kids end up caught in the middle of a credibility fight that didn't need to happen."]),
  ("If you already moved: damage control that actually works",["If the move has already happened without authorization, the priority is getting in front of it — disclosing it honestly rather than letting it surface through cross-examination, and building the strongest possible case for why the current arrangement should stay in place going forward. Waiting for the other side to raise it in court is the worst version of this conversation.","An honest, proactive approach doesn't erase the problem, but it's a far better position than getting caught."]),
 ],
 "bottom":"“Ask forgiveness, not permission” is not a legal strategy in Florida relocation cases — it's a liability. If you're thinking about moving before the paperwork is done, talk to an attorney first, not after."},

{"slug":"attorney-motion-to-withdraw-florida","cat":"Court Procedure","color":"var(--teal)","date":"2026-09-09T09:00:00",
 "mtitle":"Attorney Motion to Withdraw in FL Divorce | FMLG",
 "mdesc":"Your lawyer just filed to withdraw and your hearing is weeks away. Here's what Florida courts require — and what it means for your case timeline.",
 "h1":"Why Would My Attorney Ask to Quit My Case?",
 "summary":"When an attorney files a motion to withdraw in a Florida family law case, courts decide based on one narrow question: whether enough time remains before the next hearing for the client to secure new counsel. Here's what the court will and won't consider, and what to do after withdrawal is granted.",
 "body":[
  ("It feels personal. Legally, it usually isn't.",["When your attorney files a motion to withdraw, it can feel like abandonment, especially if a hearing is coming up. But Florida family courts treat attorney-client relationship issues as exactly that: a relationship issue, not a court issue.","Judges are not going to referee a fee dispute or a breakdown in communication between you and your lawyer. That's true even if you strongly disagree with how things ended."]),
  ("What the court will — and won't — get involved in",["A judge ruling on a motion to withdraw is answering one narrow legal question: is there enough time before the next hearing for the client to find new counsel or prepare to represent themselves? The judge is not evaluating who was right in the underlying disagreement between attorney and client.","Attorney-client privilege actively prevents the court from digging into those private communications, even when a client wants the court to hear that side of the story."]),
  ("The timeline test judges actually use",["Courts look almost entirely at the calendar. If there's a meaningful gap — weeks, not days — before the next hearing, withdrawal is typically granted, because the client has a realistic window to hire new counsel or prepare to go it alone. If a motion to withdraw shows up days before a scheduled hearing, courts are far more skeptical, because granting it would prejudice the client's ability to be ready.","That timeline test is really the whole ballgame. Everything else is secondary."]),
  ("“You have time to find new counsel” is not a suggestion",["When a judge grants a motion to withdraw, expect the order to explicitly state that the withdrawal is not grounds for a continuance. That means your hearing date doesn't move just because your representation changed. The clock the judge sets when granting withdrawal is the clock you're actually working with.","Treat that window as the real deadline it is, not a soft target."]),
  ("What to do in the days after your attorney withdraws",["Get your case file from your prior attorney immediately, including anything already filed and anything in progress. Start contacting new counsel the same week, not after you've had time to process what happened. If you can't secure new representation in time, understand exactly what proceeding pro se requires, because the court will hold you to the same evidentiary and procedural standards as an attorney.","The worst outcome isn't losing your attorney. It's losing the time you had to replace them."]),
 ],
 "bottom":"A motion to withdraw isn't a referendum on who was right. It's a deadline. Use the time the court gives you, and use it fast."},

{"slug":"pet-custody-florida-divorce","cat":"Property Division","color":"var(--chartreuse)","date":"2026-09-11T09:00:00",
 "mtitle":"Pet Custody in Florida Divorce Explained | FMLG",
 "mdesc":"Florida law treats pets as property, not children — but that doesn't mean the fight over the dog is simple. Here's how these disputes actually get resolved.",
 "h1":"Who Gets the Dog?",
 "summary":"Florida treats pets as marital property, not as children subject to a best-interest custody standard — but pet disputes in divorce are still frequently contentious. Here's what actually decides who keeps an animal, and the emotional-support-designation tactics that show up in these disputes.",
 "body":[
  ("Florida law doesn't have a “pet custody” category",["Legally, pets are property in Florida divorce, not children. There's no timesharing schedule, no best-interest-of-the-pet standard, and no support obligation for a dog or cat the way there is for kids.","That simplicity on paper almost never matches how these disputes actually feel, or how hard they get fought."]),
  ("So why does the dog fight get so ugly?",["Because a pet often isn't really about the pet. It's about who gets to keep something that represents home, routine, or comfort during a period when almost everything else is being divided up. We've seen pet disputes become more contentious than six-figure asset arguments, precisely because the stakes feel emotional rather than financial.","Once a dispute is emotional instead of practical, it tends to get used as leverage for other issues in the case, which is where things get complicated."]),
  ("The emotional-support-designation games people play",["One tactic we see: a spouse gets an emotional support animal designation for a pet from a therapist, and shortly after, weeks before a divorce filing, the other spouse gets a similar designation. The timing alone tells the story — these designations are sometimes obtained specifically to strengthen a position in an anticipated property fight, not because of a genuine, pre-existing therapeutic need.","Courts and opposing counsel notice this pattern. A designation that shows up conveniently right before filing carries a lot less weight than one with a documented history."]),
  ("What actually decides who keeps the animal",["Since pets are treated as property, factors that matter include who purchased or adopted the animal, whose name is on adoption or purchase records, and who has been the animal's primary caretaker day to day. Practical considerations — who's keeping the home, who has the space and schedule to care for the animal — carry real weight too.","An emotional support designation can be one factor a court considers, but it's rarely the deciding one, especially if it looks reactive rather than genuine."]),
  ("How to protect your case (and your pet) before it escalates",["If a pet dispute is brewing, document the practical realities early: who feeds, walks, and takes the animal to vet appointments, and any records showing that pattern over time. Avoid using the pet as a bargaining chip for other issues — courts and mediators see through it, and it can undercut your credibility on things that actually matter more, like the house or the kids.","If you're taking on the pet, also take on what comes with it, including any debt or expense tied to that decision, which can actually work in your favor at the negotiating table."]),
 ],
 "bottom":"The law treats pets as property, but people don't. Keep the practical facts front and center, and don't let an emotional fight over the dog derail the parts of your case with real financial and legal weight."},

{"slug":"competing-divorce-petitions-florida","cat":"Court Procedure","color":"var(--teal)","date":"2026-09-13T09:00:00",
 "mtitle":"Dueling Divorce Filings in Florida — What Now? | FMLG",
 "mdesc":"Two divorce petitions, two judges, one marriage. Here's how Florida courts sort out competing filings and why filing first actually matters.",
 "h1":"We Both Filed for Divorce First",
 "summary":"When both spouses file separate divorce petitions for the same marriage, Florida generally follows a first-in-time rule, with the later-filed case dismissed. Here's how competing petitions get resolved and what to do if you're facing one.",
 "body":[
  ("Yes, this actually happens",["Two spouses, two separate divorce petitions, filed within days of each other, sometimes assigned to two different judges before anyone realizes there are competing cases about the same marriage. It sounds like a paperwork glitch. It's actually a real procedural problem that has to get untangled before the divorce itself can move forward.","If you think your spouse might file first, or you're worried about filing wrong, this is exactly the scenario that makes people nervous, often for good reason."]),
  ("Why filing first isn't just bragging rights",["Florida generally follows a first-in-time principle: the case filed first is the one that proceeds, and the later-filed case gets dismissed. That's not a technicality — it determines which judge handles the case, which county's procedures apply, and who's technically the petitioner versus respondent going forward.","Filing first also means you control the initial narrative and the initial ask, which can matter in a case where the terms are contested."]),
  ("How courts untangle two cases about the same marriage",["When two petitions exist, the standard move is a motion to dismiss the second-filed case, on the basis that the first-filed action already covers the same marriage and the same relief. Consolidation of the two cases isn't typically the right move at that stage — dismissal of the duplicate is cleaner and faster.","Complications can arise if the two filings used different names, different case details, or omitted information, all of which can slow down the cleanup, even though the underlying resolution is usually straightforward once a judge sorts out which case controls."]),
  ("What you can (and can't) do about the other filing",["You can move to dismiss the later-filed case. You generally cannot simply ignore it and hope it resolves itself — until a judge formally dismisses the duplicate, both cases technically exist, which creates confusion for everyone including the court.","If your spouse files a competing petition after you've already filed, don't panic and don't respond to it as if it's a separate legal problem. It's a procedural issue your case needs to clean up, not a second front you need to fight on."]),
  ("The real lesson: file clean, file fast, file right",["If you're the one filing, get the petition right the first time — full names, complete information, and the specific relief you want, especially anything involving real property. A rushed or incomplete filing invites exactly the kind of confusion that leads to competing cases and slows everyone down.","Speed matters, but only if the filing is also accurate. A fast, sloppy filing can cost you more time than a slightly slower, correct one."]),
 ],
 "bottom":"Competing divorce filings are a headache, not a crisis — but only if they get cleaned up quickly and correctly. File first, file complete, and don't assume the other filing will just go away on its own."},

{"slug":"default-divorce-florida","cat":"Divorce Procedure","color":"var(--orange)","date":"2026-09-15T09:00:00",
 "mtitle":"Default Divorce in Florida: What to Know | FMLG",
 "mdesc":"If your spouse never responds to the divorce petition, Florida law lets you move forward without them — but only if you follow the rules exactly.",
 "h1":"What If My Spouse Ignores the Divorce Papers?",
 "summary":"Florida allows a divorce to proceed to a default judgment when a served spouse fails to respond — but the process depends on precise compliance with Financial Affidavit service rules and correct pleading of any request for real property or unequal distribution. Here's how a default divorce gets finalized.",
 "body":[
  ("Silence doesn't stop a divorce in Florida",["A spouse who refuses to respond to divorce papers doesn't get to hold the process hostage. Florida law allows a case to proceed to a default judgment if the other party is properly served and simply doesn't respond within the required time.","That said, “properly served” and “correctly documented” are doing a lot of work in that sentence, and it's exactly where default cases go wrong."]),
  ("How a default actually gets entered",["Once a spouse is served and fails to file a response within the statutory window, the filing party can request a clerk's default. From there, the case moves toward a default final hearing, where the court finalizes the divorce and the terms requested in the petition without the non-responsive spouse's participation.","It sounds simple, and for straightforward cases, it largely is. The complexity shows up around what exactly can be granted at that hearing."]),
  ("The paperwork detail that can sink an otherwise clean default",["Florida procedural rules require that a Financial Affidavit be served alongside the initial divorce petition. Skip that step, and opposing counsel — or the defaulted spouse if they eventually appear — can move to dismiss based on the omission. Once the case is properly underway, later financial affidavit updates only need to be mailed to the respondent's last known address, with a certificate of service filed.","That one document, served at the right moment, is often the difference between a clean default and a case that gets kicked back to square one."]),
  ("What you can ask for — and what requires more paperwork",["General equitable distribution language in a petition is enough to divide most personal property at a default hearing, as long as every asset is listed on the Financial Affidavit. But if real property is involved, or you're asking for an unequal distribution in your favor, the petition typically needs to specifically plead that, which may mean amending and re-serving before you can proceed.","Skipping that step doesn't just risk denial of the request. It can delay the entire default hearing while the petition gets fixed."]),
  ("Getting to your default hearing without delay",["If there's a lease or shared property tied to a timeline, like a lease expiring on a set date, it's often smarter to skip filing temporary relief motions that won't be heard before that date anyway, and instead move straight toward the uncontested default final hearing. Temporary motions can feel productive, but if the math shows they won't be resolved before the underlying issue resolves itself, they're just delay dressed up as action.","The fastest path through a default case is usually the most boring one: file everything correctly the first time, serve what's required when it's required, and go straight to the hearing."]),
 ],
 "bottom":"A non-responsive spouse doesn't stop your divorce, but sloppy paperwork will. Serve the Financial Affidavit correctly, plead for exactly what you're entitled to, and don't let avoidable procedural gaps turn a simple default into a delayed one."},
]

plan=[]
for p in POSTS:
    open(os.path.join(OUT,p["slug"]+".html"),"w").write(render(p))
    plan.append({"slug":p["slug"],"title":p["mtitle"],"mdesc":p["mdesc"],"date":p["date"],
      "file":os.path.join(OUT,p["slug"]+".html")})
json.dump(plan,open(os.path.join(BASE,"posts_plan.json"),"w"),indent=1)
print("posts built:",len(plan))
for pl in plan: print(" ",pl["date"][:10],pl["slug"], os.path.getsize(pl["file"]),"bytes")
